### ISSUE TITLE
a general question regarding videogpt

### ISSUE THREAD

**Issue by dialuser** [sihyun-yu/PVDM#13]
Hi your paper shows PVDM beat VideoGPT by a large margin. I wonder if you can offer more insights. VideoGPT also uses a two step process, first training a VQVAE, and then end-to-end autoregression. Do you think the main difference lies in the diffusion part? Thanks.

**Comment by sihyun-yu** [comment]
There are two main differences: (1) we use triplane latents of cubic tensor and (2) and we use strong diffusion model.
