### ISSUE TITLE
GPU memory needed to train AE？

### ISSUE THREAD

**Issue by DeqiangXIA** [sihyun-yu/PVDM#15]
Hi! Thanks for your paper and code. Can you tell me how much gpu memory is needed to train AE? Is 24GB enough? Thanks again.

**Comment by sihyun-yu** [comment]
For the config that I provided, 24GB would de slightly not enough. You may decrease the channel size a bit to run under 24GB limits; we internally checked decreasing it slightly does not degrade performance a lot

**Comment by JunyaoHu** [comment]
Hello, what is "slightly not enough"? I want to know the exact number, because I can't train this AE on 16*256*256 video size by 1 batch size even with a 45G A40 GPU. 

![image](https://github.com/sihyun-yu/PVDM/assets/67564714/c21fc711-381c-4ef0-bfce-64763e8ad5c3)
