### ISSUE TITLE
RuntimeError：Default process group has not been initialized, please make sure to call init_process_group.

### ISSUE THREAD

**Issue by fourcake** [sihyun-yu/PVDM#17]
When I use the sky data set and set n_gpus to 1, I try to run first_stage, "res.append(model(res[-1]))" at line 207 in ".loss/perceptual.py" reports an error "RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.”.  Why is there such a problem

**Comment by sihyun-yu** [comment]
Hi,

Can you decrease the batch_size to 1 and decrease the channel size in config then try it again?

**Comment by fourcake** [comment]
This should have nothing to do with the size of my storage. My device is two RTX4090 gpu, and each has 24G memory, when running on multiple gpus, it will tell me that the number of channels does not match: "RuntimeError: Given groups=1, weight of size [64, 3, 4, 4], expected input[1, 64, 33, 33] to have 3 channels, but got 64 channels instead".But when running on a single GPU, it still reports "RuntimeError('Default process group has not been initialized, please make sure to call init_process_group.')"

**Comment by sihyun-yu** [comment]
Can you provide me a line number (with file name) where the error "RuntimeError: Given groups=1, weight of size [64, 3, 4, 4], expected input[1, 64, 33, 33] to have 3 channels, but got 64 channels instead" occurs?

**Comment by xiefan233** [comment]
You need to change the SyncBatchNorm that appears in the code to BatchNormxd(x=1or 2 or 3) depending on the specific situation.

**Comment by TousenKaname** [comment]
Hi, do you solve the problem? Thanks!
