### ISSUE TITLE
Release of pretrain autoencoder

### ISSUE THREAD

**Issue by antonibigata** [sihyun-yu/PVDM#2]
Hi,

Thank you very much for releasing the code, the paper is super interesting.
Do you plan to also release the weights of the autoencoder?

Best,

**Comment by sihyun-yu** [comment]
Hi,

Thank you for kind words! Yes, as mentioned in README, we are planning to release the checkpoints with evaluation scripts once the refactoring of those parts is done.

**Comment by papasanimohansrinivas** [comment]
Any eta for releasing the model weights @sihyun-yu

**Comment by dinghongsong** [comment]
Hi,

Thanks for opening source. Can you tell us where to find "ucfTrainTestlist" file? 
https://github.com/sihyun-yu/PVDM/blob/main/tools/dataloader.py#:~:text=self.annotation_path%20%3D%20os.path.join(video_root%2C%20%27ucfTrainTestlist%27)
 
Best,

**Comment by sihyun-yu** [comment]
Hi, we are planning to release the model weight this week. @papasanimohansrinivas Sorry for being late, I am a bit busy these days due to other stuffs.
@dinghongsong Did you solve this issue?

**Comment by alexbruf** [comment]
@sihyun-yu Any update on when you plan on releasing the weights? This project is amazing.

**Comment by TaengguTae** [comment]
Hi, thanks for this amazing work. When I am trying run the code, some errors occur which tell me that there is no 'ucfTrainTestlist' file. Could you tell me how to get this file or is there anything wrong?

**Comment by G-U-N** [comment]
@sihyun-yu Amazing Project! Any plan for releasing the pretrained autoencoder weights? Thanks.

**Comment by sihyun-yu** [comment]
Sorry for all being late.
I need some layer name updates in previous checkpoints due to the code refactoring I did --- due to other many stuffs that I am working, I am a bit busy now and unavailable to do that. Will notify all of you one this process is done.

**Comment by ligenjie** [comment]
Amazing Project! Any plan for releasing the pretrained autoencoder weights? Thanks. @sihyun-yu

**Comment by ligenjie** [comment]
Hi,

Thanks for opening source. Can you tell us where to find "ucfTrainTestlist" file?
https://github.com/sihyun-yu/PVDM/blob/main/tools/dataloader.py#:~:text=self.annotation_path%20%3D%20os.path.join(video_root%2C%20%27ucfTrainTestlist%27)

Best,

**Comment by amaguri0408** [comment]
@ligenjie @dinghongsong @TaengguTae 

It could be downloaded from the following link on the UCF-101 [download page](https://www.crcv.ucf.edu/data/UCF101.php).

> The Train/Test Splits for Action Recognition on UCF101 data set can be downloaded by [clicking here](https://www.crcv.ucf.edu/data/UCF101/UCF101TrainTestSplits-RecognitionTask.zip).

**Comment by Wonder1905** [comment]
Any checkpoint released and I missed it?
BTW the model was pretrained on larger datasets, couldnt see it in the paper and it seems wierd not to do that?

**Comment by sihyun-yu** [comment]
Just released the autoencoder checkpoints.
