### ISSUE TITLE
Regarding training issue and artifact issue

### ISSUE THREAD

**Issue by xiefan233** [sihyun-yu/PVDM#23]
Hello, sorry to bother you. I'm studying your work recently, and I have a few questions I'd like to ask you.
①Taking training UCF101 as an example, how many steps did you train when training the diffusion model? What equipment was used and how long did it take?
②When training the diffusion model, I trained it on 4 a100 GPUs (40GB) for six days, and trained about 250,000 steps. The test results on the UCF101 data set are very good. Then I used this model to test videos from the WebVid-10M dataset and found that there are many artifacts in the generated videos, which are very similar to other people's actions. **I don't understand why these artifacts appear**, so I want to ask you. Is it because the training is not enough? (I only trained for 250,000 steps)
Below is the resulting predicted video. The second example is a man holding a remote control. From this example, we can see that there are obvious artifacts in the generated part, which may be the characteristics or actions of other characters.

https://user-images.githubusercontent.com/44406605/234668800-2eac3db0-7451-428f-8a2a-c0cad27fcddc.mp4

**Comment by sihyun-yu** [comment]
Hi,

Thank you for pointing out this issue. 

I hypothesize this is because UCF101 is a relatively small dataset consisting of <10,000 video data, which means it would be difficult to generalize to the other datasets (WebVid-10M) even if the dataset is seemingly similar.
