### ISSUE TITLE
.yaml file missing

### ISSUE THREAD

**Issue by Shivam101s** [sihyun-yu/PVDM#28]
While running the script for Diffusion Model, it gives error saying "No such file or directory: '/home/........./PVDM/configs/latent-diffusion/ucf101-ldm-kl-3_res128.yaml'. This error pops up when I give this argument "--first_model 'results/first_stage_main_gan_UCF101_42/model_last.pth' " from the diffusion model script. Does it means the "ucf101-ldm-kl-3_res128.yaml " is missing from the configs/latent-diffusion file ? Help in this matter will be really appreciated.

**Comment by sihyun-yu** [comment]
Please see this issue: https://github.com/sihyun-yu/PVDM/issues/21#issue-1673492540
