### ISSUE TITLE
The file 'i3d_pretrained_400.pt' cannot download. 

### ISSUE THREAD

**Issue by sunmeng7** [sihyun-yu/PVDM#3]
Thank you for your outstanding work.
This link https://drive.google.com/file/d/1fBNl3TS0LA5FEhZv5nMGJs2_7qQmvTmh/view to download 'i3d_pretrained_400.pt'   has been cancelled.
Can you upload it again?
Thank you.

**Comment by sihyun-yu** [comment]
Hi,

Thanks for pointing out this issue. I re-uploaded the checkpoint!
