### ISSUE TITLE
Training set used as eval/test ???

### ISSUE THREAD

**Issue by PallottaEnrico** [sihyun-yu/PVDM#40]
Is there a reason behind using the training set for evaluation, or is it just a mistake?
https://github.com/sihyun-yu/PVDM/blob/793172f7acbe51036a9f2c62a6d2bd1b0a0c6d90/tools/dataloader.py#L305-L311

https://github.com/sihyun-yu/PVDM/blob/793172f7acbe51036a9f2c62a6d2bd1b0a0c6d90/exps/first_stage.py#L80

https://github.com/sihyun-yu/PVDM/blob/793172f7acbe51036a9f2c62a6d2bd1b0a0c6d90/exps/diffusion.py#L83

**Comment by sihyun-yu** [comment]
It is just for tracking the values in the evaluation. For the final evaluation in the paper we used the setup used in previous papers (StyleGAN-V).
