### ISSUE TITLE
Batch size 

### ISSUE THREAD

**Issue by andrewyu90** [sihyun-yu/PVDM#41]
For training the autoencoder.

Is it really possible to train the autoencoder with a 7-8 batch size?

As you mentioned in the paper, how can we train the autoencoder with 24 batchsize?

I am using an A6000 (48 GB), and the memory usage is already more than 22GB when the batch size is set to 1.

**Comment by Think520change** [comment]
@andreYoo Are you using a GPU to run code？I used an A40, need to change the distributed code, do you have any ideas? Thank you.

**Comment by andrewyu90** [comment]
@Think520change I am using GPU now. Can you tell me more details? I think I can help you

**Comment by sihyun-yu** [comment]
Sorry for the late reply. I used 8 gpus for experiments - which means I used a local batch size 1 per each GPU.
