### ISSUE TITLE
self._selector.poll(timeout)

### ISSUE THREAD

**Issue by cskrren** [sihyun-yu/PVDM#6]
Hello, I encountered the following problem when training on UCF101 data set. I use n_gpus=2, but I keep getting stuck on "self._selector.poll(timeout)" while training. How do you deal with it during training?
In addition, how to modify to train on a single GPU？

**Comment by sihyun-yu** [comment]
Hi,

Can you try the command `rm -rf .torch_distributed_init`?
For training on a single GPU, you may try replacing `model.module` to `model` in `tools/trainer.py`.

**Comment by cskrren** [comment]
Thanks
