### ISSUE TITLE
Is PVDM built upon Imagen Video?

### ISSUE THREAD

**Issue by nam-drun** [sihyun-yu/PVDM#8]
I guess it should since VDM's authors are the same authors for ImagenVideo but I'm not sure

**Comment by sihyun-yu** [comment]
Hi,

I have no connection with (or authors of) VDM or Imaegn-Video.

**Comment by nam-drun** [comment]
Hmm, what would you advice if I want to integrate  PVDM to GitHub Imagen pipeline by lucidrains?
